# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: touch .env
    - run: echo MONGO_URL=${{ secrets.MONGO_URL }} >> .env
    - run: echo MONGO_DATABASE=${{ secrets.MONGO_DATABASE }} >> .env
    - run: echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> .env
    - run: echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env
    - run: echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
    - run: echo TURNSTILE_KEY=${{ secrets.TURNSTILE_KEY }} >> .env
    - run: echo USER_ACCOUNTS_COLLECTION=${{ secrets.USER_ACCOUNTS_COLLECTION }} >> .env
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test


